package io.github.dkuechler.jbench.repositories;

import io.github.dkuechler.jbench.model.QuizQuestion;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@JdbcTest
class QuizQuestionRepositoryJdbcTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private ObjectMapper objectMapper;
    private QuizQuestionRepositoryJdbc repository;

    @BeforeEach
    void setUp() {
        objectMapper = new ObjectMapper();
        repository = new QuizQuestionRepositoryJdbc(jdbcTemplate, objectMapper);

        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS quiz_questions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                question TEXT NOT NULL,
                options TEXT NOT NULL,
                correct_answer_index INTEGER NOT NULL,
                category VARCHAR(100) NOT NULL
            )
        """);
    }

    @Test
    void shouldSaveQuestionAndReturnWithGeneratedId() {
        QuizQuestion question = new QuizQuestion(
            "What is the capital of France?",
            List.of("London", "Paris", "Madrid", "Rome"),
            1,
            "Geography"
        );

        QuizQuestion savedQuestion = repository.save(question);

        assertNotNull(savedQuestion);
        assertNotNull(savedQuestion.getId());
        assertTrue(savedQuestion.getId() > 0);
        assertEquals(question.getQuestion(), savedQuestion.getQuestion());
        assertEquals(question.getOptions(), savedQuestion.getOptions());
    }

    @Test
    void shouldPersistDataCorrectlyInDatabase() {
        QuizQuestion question = new QuizQuestion(
            "What is 2 + 2?",
            List.of("3", "4", "5"),
            1,
            "Math"
        );

        QuizQuestion saved = repository.save(question);

        String sql = "SELECT COUNT(*) FROM quiz_questions WHERE id = ?";
        Integer count = jdbcTemplate.queryForObject(sql, Integer.class, saved.getId());
        assertEquals(1, count);
    }

    @Test
    void shouldSerializeOptionsToJson() {
        QuizQuestion question = new QuizQuestion(
            "Test question?",
            List.of("Option A", "Option B"),
            0,
            "Test"
        );

        QuizQuestion saved = repository.save(question);

        String sql = "SELECT options FROM quiz_questions WHERE id = ?";
        String storedJson = jdbcTemplate.queryForObject(sql, String.class, saved.getId());
        
        assertNotNull(storedJson);
        assertTrue(storedJson.contains("Option A"));
        assertTrue(storedJson.startsWith("["));
        assertTrue(storedJson.endsWith("]"));
    }
}