CREATE TABLE IF NOT EXISTS app_user (
    id UUID PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS measurement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    measurement_type VARCHAR(50) NOT NULL,
    value_numeric DOUBLE PRECISION NOT NULL,
    recorded_at TIMESTAMP NOT NULL,
    external_source_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT unique_user_type_source UNIQUE (user_id, measurement_type, external_source_id),
    CONSTRAINT positive_measurement_value CHECK (value_numeric >= 0)
);

CREATE INDEX IF NOT EXISTS measurement_user_type_time ON measurement(user_id, measurement_type, recorded_at DESC);

CREATE TABLE IF NOT EXISTS workout (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    workout_type VARCHAR(50) NOT NULL,
    external_id VARCHAR(255) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    duration_seconds INT,
    active_duration_seconds INT,
    calories_burned DOUBLE PRECISION,
    distance_meters DOUBLE PRECISION,
    avg_heart_rate INT,
    max_heart_rate INT,
    min_heart_rate INT,
    route_available BOOLEAN DEFAULT FALSE,
    source_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT unique_workout_user_external UNIQUE (user_id, external_id)
);

CREATE INDEX IF NOT EXISTS workout_user_start_time ON workout(user_id, start_time DESC);

CREATE TABLE IF NOT EXISTS workout_heart_rate_sample (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id BIGINT NOT NULL REFERENCES workout(id) ON DELETE CASCADE,
    sample_time TIMESTAMP NOT NULL,
    bpm INT NOT NULL,
    source_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_workout_sample_ts_source UNIQUE (workout_id, sample_time, source_id)
);

CREATE INDEX IF NOT EXISTS ix_workout_hr_sample_time ON workout_heart_rate_sample(workout_id, sample_time DESC);

CREATE TABLE IF NOT EXISTS ai_insight_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    requested_at TIMESTAMP NOT NULL,
    tokens_used INT,
    model_used VARCHAR(50),
    success BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_ai_insight_user_time ON ai_insight_request(user_id, requested_at DESC);
