CREATE TABLE IF NOT EXISTS app_user (
    id UUID PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS measurement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    measurement_type VARCHAR(50) NOT NULL,
    value_numeric DOUBLE PRECISION NOT NULL,
    recorded_at TIMESTAMP NOT NULL,
    external_source_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT unique_user_type_source UNIQUE (user_id, measurement_type, external_source_id),
    CONSTRAINT positive_measurement_value CHECK (value_numeric >= 0)
);

CREATE INDEX measurement_user_type_time ON measurement(user_id, measurement_type, recorded_at DESC);

CREATE TABLE IF NOT EXISTS workout (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    workout_type VARCHAR(50) NOT NULL,
    external_id VARCHAR(255) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    duration_seconds INT,
    active_duration_seconds INT,
    calories_burned DOUBLE PRECISION,
    distance_meters DOUBLE PRECISION,
    avg_heart_rate INT,
    max_heart_rate INT,
    min_heart_rate INT,
    route_available BOOLEAN DEFAULT FALSE,
    source_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT unique_workout_user_external UNIQUE (user_id, external_id)
);

CREATE INDEX workout_user_start_time ON workout(user_id, start_time DESC);
